slc6-gcc48:
  tags:
    - docker
  image: cern/slc6-base
  script:
    - export G4INSTALL="/cvmfs/sft.cern.ch/lcg/releases/LCG_84/../Geant4/10.02-7c0e3/x86_64-slc6-gcc48-opt"
    - export G4ENV_INIT="$G4INSTALL/bin/geant4.sh"
    - export G4SYSTEM="Linux-g++"
    - test -r ${G4ENV_INIT} && { cd $(dirname ${G4ENV_INIT}) ; . ./$(basename ${G4ENV_INIT}) ; cd $OLDPWD ; }
    - cd /cvmfs/sft.cern.ch/lcg/releases/ROOT/6.06.02-6cc9c/x86_64-slc6-gcc48-opt
    - . ./bin/thisroot.sh 
