slc6-gcc48:
  tags:
    - docker
  image: clicdp/slc6-base
  script:
    - export GCC_VERSION="4.8.5"
    - export BUILD_TYPE="opt"
    - source .gitlab-ci.d/init_x86_64.sh
    - mkdir build 
    - cd build
    - cmake -GNinja -D DD4HEP_USE_GEANT4=ON -D DD4HEP_USE_BOOST=ON -DBoost_NO_BOOST_CMAKE=ON -D DD4HEP_USE_LCIO=ON -D BUILD_TESTING=ON -DCLHEP_DIR=$CLHEP -D Geant4_DIR=$G4INSTALL/lib64/Geant4-10.2.2 -D DD4HEP_USE_CXX11=ON ..        
    - ninja
    - ninja install
    - . ../bin/thisdd4hep.sh
    - ctest --output-on-failure -j4
    - cd ../examples/
    - mkdir build
    - cd build
    - cmake -GNinja ..
    - ninja
    - ninja install
    - ctest --output-on-failure
    - cd ../..
    - rm -rf .git
    - sshpass -p $CLICTEL_PASS rsync -arv -e ssh --delete . clictel@lxplus:/afs/cern.ch/eng/clic/software/DD4hep/x86_64-slc6-gcc48-opt

slc6-gcc49:
  tags:
    - docker
  image: clicdp/slc6-base
  script:
    - export GCC_VERSION="4.9.3"
    - export BUILD_TYPE="opt"
    - source .gitlab-ci.d/init_x86_64.sh
    - mkdir build 
    - cd build
    - cmake -GNinja -D DD4HEP_USE_GEANT4=ON -D DD4HEP_USE_BOOST=ON -DBoost_NO_BOOST_CMAKE=ON -D DD4HEP_USE_LCIO=ON -D BUILD_TESTING=ON -DCLHEP_DIR=$CLHEP -D Geant4_DIR=$G4INSTALL/lib64/Geant4-10.2.2 -D DD4HEP_USE_CXX11=ON ..        
    - ninja
    - ninja install
    - . ../bin/thisdd4hep.sh
    - ctest --output-on-failure -j4
    - cd ../examples/
    - mkdir build
    - cd build
    - cmake -GNinja ..
    - ninja
    - ninja install
    - ctest --output-on-failure
    - cd ../..
    - rm -rf .git
    - sshpass -p $CLICTEL_PASS rsync -arv -e ssh --delete . clictel@lxplus:/afs/cern.ch/eng/clic/software/DD4hep/x86_64-slc6-gcc49-opt

centos7-gcc49:
  tags:
    - docker
  image: clicdp/cc7-base
  script:
    - export GCC_VERSION="4.9.3"
    - export BUILD_TYPE="opt"
    - source .gitlab-ci.d/init_x86_64.sh
    - mkdir build 
    - cd build
    - cmake -GNinja -D DD4HEP_USE_GEANT4=ON -D DD4HEP_USE_BOOST=ON -DBoost_NO_BOOST_CMAKE=ON -D DD4HEP_USE_LCIO=ON -D BUILD_TESTING=ON -DCLHEP_DIR=$CLHEP -D Geant4_DIR=$G4INSTALL/lib64/Geant4-10.2.2 -D DD4HEP_USE_CXX11=ON ..        
    - ninja
    - ninja install
    - . ../bin/thisdd4hep.sh
    - ctest --output-on-failure -j4
    - cd ../examples/
    - mkdir build
    - cd build
    - cmake -GNinja ..
    - ninja
    - ninja install
    - ctest --output-on-failure
    - cd ../..
    - rm -rf .git
    - sshpass -p $CLICTEL_PASS rsync -arv -e ssh --delete . clictel@lxplus:/afs/cern.ch/eng/clic/software/DD4hep/x86_64-centos7-gcc49-opt
