before_script:
    #pre-installation script
    - yum install make -y
    - yum install which -y
centos7-gcc48:
  tags:
    - docker
  image: cern/cc7-base
  script:
    - source .gitlab-ci.d/init_x86_64-centos7-gcc48-opt.sh
    - mkdir build 
    - cd build
    - cmake -D DD4HEP_USE_GEANT4=1 -D DD4HEP_USE_BOOST=ON -DBoost_NO_BOOST_CMAKE=ON -D DD4HEP_USE_LCIO=ON -D BUILD_TESTING=ON -D CLHEP_DIR=$CLHEP -D DD4HEP_USE_GEAR=1 -DCMAKE_CXX_COMPILER=`which g++` -DCMAKE_C_COMPILER=`which gcc` ..
    - make -j4
    - make install


centos7-gcc49:
  tags:
    - docker
  image: cern/cc7-base
  script:
    - source .gitlab-ci.d/init_x86_64-centos7-gcc49-opt.sh
    - mkdir build 
    - cd build
    - cmake -D DD4HEP_USE_GEANT4=1 -D DD4HEP_USE_BOOST=ON -DBoost_NO_BOOST_CMAKE=ON -D DD4HEP_USE_LCIO=ON -D BUILD_TESTING=ON -D CLHEP_DIR=$CLHEP -D DD4HEP_USE_GEAR=1 -DCMAKE_CXX_COMPILER=`which g++` -DCMAKE_C_COMPILER=`which gcc` ..
    - make -j4
    - make install


slc6-gcc48:
  tags:
    - docker
  image: cern/slc6-base
  script:
    - source .gitlab-ci.d/init_x86_64-slc6-gcc48-opt.sh
    - mkdir build 
    - cd build
    - cmake -D DD4HEP_USE_GEANT4=1 -D DD4HEP_USE_BOOST=ON -DBoost_NO_BOOST_CMAKE=ON -D DD4HEP_USE_LCIO=ON -D BUILD_TESTING=ON -D CLHEP_DIR=$CLHEP -D DD4HEP_USE_GEAR=1 -DCMAKE_CXX_COMPILER=`which g++` -DCMAKE_C_COMPILER=`which gcc` ..
    - make -j4
    - make install


slc6-gcc49:
  tags:
    - docker
  image: cern/slc6-base
  script:
    - source .gitlab-ci.d/init_x86_64-slc6-gcc49-opt.sh
    - mkdir build 
    - cd build
    - cmake -D DD4HEP_USE_GEANT4=1 -D DD4HEP_USE_BOOST=ON -DBoost_NO_BOOST_CMAKE=ON -D DD4HEP_USE_LCIO=ON -D BUILD_TESTING=ON -D CLHEP_DIR=$CLHEP -D DD4HEP_USE_GEAR=1 -DCMAKE_CXX_COMPILER=`which g++` -DCMAKE_C_COMPILER=`which gcc` ..
    - make -j4
    - make install
