slc6-gcc48:
  tags:
    - docker
  image: clicdp/slc6-base
  script:
    - rm /bin/sh && ln -s /bin/bash /bin/sh
    - cd /cvmfs/sft.cern.ch/lcg/releases/LCG_84/ROOT/6.06.02/x86_64-slc6-gcc48-opt/
    - . bin/thisroot.sh
