name: linux

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        LCG: ["LCG_99/x86_64-centos7-clang10-opt",
              "LCG_99/x86_64-centos7-gcc10-opt"]
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: aidasoft/run-lcg-view@main
      with:
        unpacked: 'false'
        release-platform: ${{ matrix.LCG }}
        run: |
          mkdir build
          cd build
          unset CPATH
          cmake -GNinja \
            -DDD4HEP_USE_GEANT4=ON \
            -DBoost_NO_BOOST_CMAKE=ON \
            -DDD4HEP_USE_LCIO=ON \
            -DDD4HEP_USE_EDM4HEP=ON \
            -DDD4HEP_USE_TBB=ON \
            -DDD4HEP_USE_HEPMC3=ON \
            -DDD4HEP_BUILD_DEBUG=OFF \
            -DBUILD_TESTING=ON \
            -DDD4HEP_DEBUG_CMAKE=ON \
            -DDD4HEP_USE_XERCESC=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always"  \
            -DCMAKE_CXX_STANDARD=17 ..
          ninja install
          . ../bin/thisdd4hep.sh
          ctest --output-on-failure -j4
          cd ../examples/
          mkdir build
          cd build
          cmake -GNinja \
            -DBoost_NO_BOOST_CMAKE=ON \
            -DDD4HEP_USE_XERCESC=ON \
            -DCMAKE_CXX_STANDARD=17 ..
          ninja install
          ctest --output-on-failure -j2
  unpacked:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        LCG: ["LCG_99/x86_64-centos7-clang10-opt",
              "LCG_99/x86_64-centos7-gcc10-opt"]
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: aidasoft/run-lcg-view@main
      with:
        unpacked: 'true'
        release-platform: ${{ matrix.LCG }}
        run: |
          mkdir build
          cd build
          unset CPATH
          cmake -GNinja \
            -DDD4HEP_USE_GEANT4=ON \
            -DBoost_NO_BOOST_CMAKE=ON \
            -DDD4HEP_USE_LCIO=ON \
            -DDD4HEP_USE_EDM4HEP=ON \
            -DDD4HEP_USE_TBB=ON \
            -DDD4HEP_USE_HEPMC3=ON \
            -DDD4HEP_BUILD_DEBUG=OFF \
            -DBUILD_TESTING=ON \
            -DDD4HEP_DEBUG_CMAKE=ON \
            -DDD4HEP_USE_XERCESC=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always"  \
            -DCMAKE_CXX_STANDARD=17 ..
          ninja install
          . ../bin/thisdd4hep.sh
          ctest --output-on-failure -j4
          cd ../examples/
          mkdir build
          cd build
          cmake -GNinja \
            -DBoost_NO_BOOST_CMAKE=ON \
            -DDD4HEP_USE_XERCESC=ON \
            -DCMAKE_CXX_STANDARD=17 ..
          ninja install
          ctest --output-on-failure -j2
